# Generated by Django 6.0.6 on 2026-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('request_type', models.CharField(choices=[('need', 'Потребность'), ('problem', 'Проблема'), ('task', 'Задача')], max_length=10, verbose_name='Тип обращения')),
                ('title', models.CharField(max_length=200, verbose_name='Краткое название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('expected_result', models.TextField(blank=True, max_length=2000, verbose_name='Ожидаемый результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка бизнеса',
                'verbose_name_plural': 'Заявки бизнеса',
                'ordering': ['-created_at'],
            },
        ),
    ]
