# Generated by Django 6.0.6 on 2026-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='interaction_format',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Формат взаимодействия'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='need',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Потребность'),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('need', 'Потребность'), ('problem', 'Проблема'), ('task', 'Задача')], max_length=10, verbose_name='Тип обращения'),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
