# Generated by Django 6.0.6 on 2026-09-23 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_businessrequest_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessrequest',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Заявка бизнеса', 'verbose_name_plural': 'Заявки бизнеса'},
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='owner_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, verbose_name='Ключ сессии автора'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Версия карточки'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена')], default='draft', editable=False, max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата изменения'),
        ),
    ]
